create or replace view VIS_MATRIZ_RIESGO AS 
SELECT ID_MATRIZ_RIESGO, NOMBRE, FECHA_DESDE, 
   FECHA_HASTA, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA
FROM PRI_MATRIZ_RIESGO order by id_matriz_riesgo;


create or replace view VIS_VARIABLE AS 
SELECT ID_VARIABLE, NOMBRE, FUENTE_SISTEMA, 
   FUENTE_INFORMACION, FORMULA, PERIODICIDAD, 
   PROCEDIMIENTO_BASE_DATOS, ESTADO, USUARIO_AUDITORIA, 
   FECHA_AUDITORIA
FROM PRI_VARIABLE order by id_variable;

create or replace view VIS_SEGMENTO AS 
SELECT ID_SEGMENTO, NOMBRE, ESTADO, 
   USUARIO_AUDITORIA, FECHA_AUDITORIA
FROM PRI_SEGMENTO order by id_segmento;