SET DEFINE OFF;
Insert into PRI_MATRIZ_RIESGO_CUADRANTE
   (ID_MATRIZ_RIESGO_CUADRANTE, ID_MATRIZ_RIESGO, NUMERO_CUADRANTE, VALOR_EJE_X_DESDE, VALOR_EJE_X_HASTA, VALOR_EJE_Y_DESDE, VALOR_EJE_Y_HASTA, COLOR, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (1, 1, 1, 0, 0.25, 
    0, 0.2, 'VERDE', 'ACTIVO', 'user_sat', 
    TO_DATE('01/18/2022 20:04:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_CUADRANTE
   (ID_MATRIZ_RIESGO_CUADRANTE, ID_MATRIZ_RIESGO, NUMERO_CUADRANTE, VALOR_EJE_X_DESDE, VALOR_EJE_X_HASTA, VALOR_EJE_Y_DESDE, VALOR_EJE_Y_HASTA, COLOR, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (2, 1, 2, 0.25, 0.5, 
    0, 0.2, 'VERDE', 'ACTIVO', 'user_sat', 
    TO_DATE('01/18/2022 20:04:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_CUADRANTE
   (ID_MATRIZ_RIESGO_CUADRANTE, ID_MATRIZ_RIESGO, NUMERO_CUADRANTE, VALOR_EJE_X_DESDE, VALOR_EJE_X_HASTA, VALOR_EJE_Y_DESDE, VALOR_EJE_Y_HASTA, COLOR, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (3, 1, 3, 0, 0.25, 
    0.2, 0.4, 'VERDE', 'ACTIVO', 'user_sat', 
    TO_DATE('01/18/2022 20:04:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_CUADRANTE
   (ID_MATRIZ_RIESGO_CUADRANTE, ID_MATRIZ_RIESGO, NUMERO_CUADRANTE, VALOR_EJE_X_DESDE, VALOR_EJE_X_HASTA, VALOR_EJE_Y_DESDE, VALOR_EJE_Y_HASTA, COLOR, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (4, 1, 4, 0.5, 0.75, 
    0, 0.2, 'AMARILLO', 'ACTIVO', 'user_sat', 
    TO_DATE('01/18/2022 20:04:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_CUADRANTE
   (ID_MATRIZ_RIESGO_CUADRANTE, ID_MATRIZ_RIESGO, NUMERO_CUADRANTE, VALOR_EJE_X_DESDE, VALOR_EJE_X_HASTA, VALOR_EJE_Y_DESDE, VALOR_EJE_Y_HASTA, COLOR, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (5, 1, 5, 0.25, 0.5, 
    0.2, 0.4, 'AMARILLO', 'ACTIVO', 'user_sat', 
    TO_DATE('01/18/2022 20:04:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_CUADRANTE
   (ID_MATRIZ_RIESGO_CUADRANTE, ID_MATRIZ_RIESGO, NUMERO_CUADRANTE, VALOR_EJE_X_DESDE, VALOR_EJE_X_HASTA, VALOR_EJE_Y_DESDE, VALOR_EJE_Y_HASTA, COLOR, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (6, 1, 6, 0, 0.25, 
    0.4, 0.6, 'AMARILLO', 'ACTIVO', 'user_sat', 
    TO_DATE('01/18/2022 20:04:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_CUADRANTE
   (ID_MATRIZ_RIESGO_CUADRANTE, ID_MATRIZ_RIESGO, NUMERO_CUADRANTE, VALOR_EJE_X_DESDE, VALOR_EJE_X_HASTA, VALOR_EJE_Y_DESDE, VALOR_EJE_Y_HASTA, COLOR, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (7, 1, 7, 0.75, 1, 
    0, 0.2, 'AMARILLO', 'ACTIVO', 'user_sat', 
    TO_DATE('01/18/2022 20:04:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_CUADRANTE
   (ID_MATRIZ_RIESGO_CUADRANTE, ID_MATRIZ_RIESGO, NUMERO_CUADRANTE, VALOR_EJE_X_DESDE, VALOR_EJE_X_HASTA, VALOR_EJE_Y_DESDE, VALOR_EJE_Y_HASTA, COLOR, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (8, 1, 8, 0.5, 0.75, 
    0.2, 0.4, 'AMARILLO', 'ACTIVO', 'user_sat', 
    TO_DATE('01/18/2022 20:04:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_CUADRANTE
   (ID_MATRIZ_RIESGO_CUADRANTE, ID_MATRIZ_RIESGO, NUMERO_CUADRANTE, VALOR_EJE_X_DESDE, VALOR_EJE_X_HASTA, VALOR_EJE_Y_DESDE, VALOR_EJE_Y_HASTA, COLOR, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (9, 1, 9, 0.25, 0.5, 
    0.4, 0.6, 'AMARILLO', 'ACTIVO', 'user_sat', 
    TO_DATE('01/18/2022 20:04:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_CUADRANTE
   (ID_MATRIZ_RIESGO_CUADRANTE, ID_MATRIZ_RIESGO, NUMERO_CUADRANTE, VALOR_EJE_X_DESDE, VALOR_EJE_X_HASTA, VALOR_EJE_Y_DESDE, VALOR_EJE_Y_HASTA, COLOR, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (10, 1, 10, 0, 0.25, 
    0.6, 0.8, 'AMARILLO', 'ACTIVO', 'user_sat', 
    TO_DATE('01/18/2022 20:04:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_CUADRANTE
   (ID_MATRIZ_RIESGO_CUADRANTE, ID_MATRIZ_RIESGO, NUMERO_CUADRANTE, VALOR_EJE_X_DESDE, VALOR_EJE_X_HASTA, VALOR_EJE_Y_DESDE, VALOR_EJE_Y_HASTA, COLOR, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (11, 1, 11, 0.75, 1, 
    0.2, 0.4, 'NARANJA', 'ACTIVO', 'user_sat', 
    TO_DATE('01/18/2022 20:04:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_CUADRANTE
   (ID_MATRIZ_RIESGO_CUADRANTE, ID_MATRIZ_RIESGO, NUMERO_CUADRANTE, VALOR_EJE_X_DESDE, VALOR_EJE_X_HASTA, VALOR_EJE_Y_DESDE, VALOR_EJE_Y_HASTA, COLOR, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (12, 1, 12, 0.5, 0.75, 
    0.4, 0.6, 'NARANJA', 'ACTIVO', 'user_sat', 
    TO_DATE('01/18/2022 20:04:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_CUADRANTE
   (ID_MATRIZ_RIESGO_CUADRANTE, ID_MATRIZ_RIESGO, NUMERO_CUADRANTE, VALOR_EJE_X_DESDE, VALOR_EJE_X_HASTA, VALOR_EJE_Y_DESDE, VALOR_EJE_Y_HASTA, COLOR, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (13, 1, 13, 0.25, 0.5, 
    0.6, 0.8, 'NARANJA', 'ACTIVO', 'user_sat', 
    TO_DATE('01/18/2022 20:04:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_CUADRANTE
   (ID_MATRIZ_RIESGO_CUADRANTE, ID_MATRIZ_RIESGO, NUMERO_CUADRANTE, VALOR_EJE_X_DESDE, VALOR_EJE_X_HASTA, VALOR_EJE_Y_DESDE, VALOR_EJE_Y_HASTA, COLOR, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (14, 1, 14, 0, 0.25, 
    0.8, 1, 'NARANJA', 'ACTIVO', 'user_sat', 
    TO_DATE('01/18/2022 20:04:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_CUADRANTE
   (ID_MATRIZ_RIESGO_CUADRANTE, ID_MATRIZ_RIESGO, NUMERO_CUADRANTE, VALOR_EJE_X_DESDE, VALOR_EJE_X_HASTA, VALOR_EJE_Y_DESDE, VALOR_EJE_Y_HASTA, COLOR, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (15, 1, 15, 0.75, 1, 
    0.4, 0.6, 'NARANJA', 'ACTIVO', 'user_sat', 
    TO_DATE('01/18/2022 20:04:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_CUADRANTE
   (ID_MATRIZ_RIESGO_CUADRANTE, ID_MATRIZ_RIESGO, NUMERO_CUADRANTE, VALOR_EJE_X_DESDE, VALOR_EJE_X_HASTA, VALOR_EJE_Y_DESDE, VALOR_EJE_Y_HASTA, COLOR, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (16, 1, 16, 0.5, 0.75, 
    0.6, 0.8, 'NARANJA', 'ACTIVO', 'user_sat', 
    TO_DATE('01/18/2022 20:04:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_CUADRANTE
   (ID_MATRIZ_RIESGO_CUADRANTE, ID_MATRIZ_RIESGO, NUMERO_CUADRANTE, VALOR_EJE_X_DESDE, VALOR_EJE_X_HASTA, VALOR_EJE_Y_DESDE, VALOR_EJE_Y_HASTA, COLOR, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (17, 1, 17, 0.25, 0.5, 
    0.8, 1, 'NARANJA', 'ACTIVO', 'user_sat', 
    TO_DATE('01/18/2022 20:04:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_CUADRANTE
   (ID_MATRIZ_RIESGO_CUADRANTE, ID_MATRIZ_RIESGO, NUMERO_CUADRANTE, VALOR_EJE_X_DESDE, VALOR_EJE_X_HASTA, VALOR_EJE_Y_DESDE, VALOR_EJE_Y_HASTA, COLOR, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (18, 1, 18, 0.75, 1, 
    0.6, 0.8, 'ROJO', 'ACTIVO', 'user_sat', 
    TO_DATE('01/18/2022 20:04:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_CUADRANTE
   (ID_MATRIZ_RIESGO_CUADRANTE, ID_MATRIZ_RIESGO, NUMERO_CUADRANTE, VALOR_EJE_X_DESDE, VALOR_EJE_X_HASTA, VALOR_EJE_Y_DESDE, VALOR_EJE_Y_HASTA, COLOR, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (19, 1, 19, 0.5, 0.75, 
    0.8, 1, 'ROJO', 'ACTIVO', 'user_sat', 
    TO_DATE('01/18/2022 20:04:40', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_CUADRANTE
   (ID_MATRIZ_RIESGO_CUADRANTE, ID_MATRIZ_RIESGO, NUMERO_CUADRANTE, VALOR_EJE_X_DESDE, VALOR_EJE_X_HASTA, VALOR_EJE_Y_DESDE, VALOR_EJE_Y_HASTA, COLOR, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (20, 1, 20, 0.75, 1, 
    0.8, 1, 'ROJO', 'ACTIVO', 'user_sat', 
    TO_DATE('01/18/2022 20:04:40', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
