SET DEFINE OFF;
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (160, 1, 5, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (161, 1, 6, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (162, 1, 7, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (163, 1, 8, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (164, 1, 9, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (165, 1, 10, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (166, 1, 11, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (167, 1, 12, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (168, 1, 13, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (169, 1, 14, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (170, 1, 15, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_X, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (171, 1, 16, '6', 
    'S', 'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (172, 1, 17, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (173, 1, 18, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_X, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (174, 1, 19, '6', 
    'S', 'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_X, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (175, 1, 20, '6', 
    'S', 'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (176, 1, 21, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (177, 1, 22, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (178, 1, 23, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (179, 1, 24, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (180, 1, 25, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (181, 1, 26, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (182, 1, 27, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (183, 1, 28, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (184, 1, 29, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_PESO_CONTRIBUYENTE, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (185, 1, 30, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_PESO_CONTRIBUYENTE, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (186, 1, 31, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (1, 1, 1, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (2, 1, 2, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (3, 1, 3, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (4, 1, 4, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (5, 1, 5, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (6, 1, 6, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (7, 1, 7, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (8, 1, 8, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (9, 1, 9, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (10, 1, 10, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (11, 1, 11, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (12, 1, 12, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (13, 1, 13, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (14, 1, 14, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (15, 1, 15, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_X, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (16, 1, 16, '1', 
    'S', 'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (17, 1, 17, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (18, 1, 18, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_X, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (19, 1, 19, '1', 
    'S', 'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_X, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (20, 1, 20, '1', 
    'S', 'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (21, 1, 21, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (22, 1, 22, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (23, 1, 23, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (24, 1, 24, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (25, 1, 25, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (26, 1, 26, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (27, 1, 27, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (28, 1, 28, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (29, 1, 29, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_PESO_CONTRIBUYENTE, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (30, 1, 30, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_PESO_CONTRIBUYENTE, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (31, 1, 31, '1', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (32, 1, 1, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (33, 1, 2, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (34, 1, 3, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (35, 1, 4, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (36, 1, 5, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (37, 1, 6, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (38, 1, 7, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (39, 1, 8, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (40, 1, 9, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (41, 1, 10, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (42, 1, 11, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (43, 1, 12, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (44, 1, 13, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (45, 1, 14, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (46, 1, 15, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_X, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (47, 1, 16, '2', 
    'S', 'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (48, 1, 17, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (49, 1, 18, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_X, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (50, 1, 19, '2', 
    'S', 'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_X, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (51, 1, 20, '2', 
    'S', 'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (52, 1, 21, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (53, 1, 22, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (54, 1, 23, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (55, 1, 24, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (56, 1, 25, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (57, 1, 26, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (58, 1, 27, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (59, 1, 28, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (60, 1, 29, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_PESO_CONTRIBUYENTE, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (61, 1, 30, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_PESO_CONTRIBUYENTE, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (62, 1, 31, '2', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_PESO_Y, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (63, 1, 1, '3', 0.05, 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_PESO_Y, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (64, 1, 2, '3', 0.05, 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (65, 1, 3, '3', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (66, 1, 4, '3', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (67, 1, 5, '3', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_PESO_Y, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (68, 1, 6, '3', 0.15, 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (69, 1, 7, '3', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (70, 1, 8, '3', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (71, 1, 9, '3', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_PESO_Y, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (72, 1, 10, '3', 0.3, 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (73, 1, 11, '3', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (74, 1, 12, '3', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (75, 1, 13, '3', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (76, 1, 14, '3', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (77, 1, 15, '3', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_PESO_Y, FUENTE_EJE_X, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (78, 1, 16, '3', 0.15, 
    'S', 'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (79, 1, 17, '3', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (80, 1, 18, '3', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_PESO_Y, FUENTE_EJE_X, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (81, 1, 19, '3', 0.1, 
    'S', 'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_X, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (82, 1, 20, '3', 
    'S', 'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_PESO_Y, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (83, 1, 21, '3', 0.2, 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (84, 1, 22, '3', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (85, 1, 23, '3', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (86, 1, 24, '3', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (87, 1, 25, '3', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (88, 1, 26, '3', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (89, 1, 27, '3', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (90, 1, 28, '3', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (91, 1, 29, '3', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_PESO_CONTRIBUYENTE, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (92, 1, 30, '3', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_PESO_CONTRIBUYENTE, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (93, 1, 31, '3', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (94, 1, 1, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (95, 1, 2, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (96, 1, 3, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (97, 1, 4, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (98, 1, 5, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (99, 1, 6, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (100, 1, 7, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (101, 1, 8, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (102, 1, 9, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (103, 1, 10, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (104, 1, 11, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (105, 1, 12, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (106, 1, 13, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (107, 1, 14, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (108, 1, 15, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_X, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (109, 1, 16, '4', 
    'S', 'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (110, 1, 17, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (111, 1, 18, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_X, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (112, 1, 19, '4', 
    'S', 'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_X, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (113, 1, 20, '4', 
    'S', 'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (114, 1, 21, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (115, 1, 22, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (116, 1, 23, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (117, 1, 24, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (118, 1, 25, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (119, 1, 26, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (120, 1, 27, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (121, 1, 28, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (122, 1, 29, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_PESO_CONTRIBUYENTE, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (123, 1, 30, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_PESO_CONTRIBUYENTE, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (124, 1, 31, '4', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (125, 1, 1, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (126, 1, 2, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (127, 1, 3, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (128, 1, 4, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (129, 1, 5, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (130, 1, 6, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (131, 1, 7, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (132, 1, 8, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (133, 1, 9, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (134, 1, 10, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (135, 1, 11, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (136, 1, 12, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (137, 1, 13, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (138, 1, 14, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (139, 1, 15, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_X, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (140, 1, 16, '5', 
    'S', 'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (141, 1, 17, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (142, 1, 18, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_X, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (143, 1, 19, '5', 
    'S', 'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_X, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (144, 1, 20, '5', 
    'S', 'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (145, 1, 21, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (146, 1, 22, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (147, 1, 23, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (148, 1, 24, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (149, 1, 25, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (150, 1, 26, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (151, 1, 27, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (152, 1, 28, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (153, 1, 29, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_PESO_CONTRIBUYENTE, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (154, 1, 30, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_PESO_CONTRIBUYENTE, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (155, 1, 31, '5', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (156, 1, 1, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (157, 1, 2, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (158, 1, 3, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
Insert into PRI_MATRIZ_RIESGO_VARIABLE
   (ID_MATRIZ_RIESGO_VARIABLE, ID_MATRIZ_RIESGO, ID_VARIABLE, ID_SEGMENTO, FUENTE_EJE_Y, ESTADO, USUARIO_AUDITORIA, FECHA_AUDITORIA)
 Values
   (159, 1, 4, '6', 
    'S', 'ACTIVO', 'USER_SAT', TO_DATE('01/18/2022 21:28:02', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
