CREATE TABLE PRI_MATRIZ_RIESGO
(
  ID_MATRIZ_RIESGO   NUMBER(10)                 NOT NULL,
  NOMBRE             VARCHAR2(200 BYTE),
  FECHA_DESDE        DATE,
  FECHA_HASTA        DATE,
  ESTADO             VARCHAR2(30 CHAR)          NOT NULL,
  USUARIO_AUDITORIA  VARCHAR2(50 CHAR)          DEFAULT USER                  NOT NULL,
  FECHA_AUDITORIA    DATE                       DEFAULT SYSDATE               NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PRI_MATRIZ_RIESGO IS 'Contiene la lista de matrices de riesgo para ubicar los perfiles de los contribuyentes';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO.ID_MATRIZ_RIESGO IS 'Identificador único de registro en PRI_MATRIZ_RIESGO';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO.FECHA_DESDE IS 'Fecha de vigencia desde de la matriz';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO.FECHA_HASTA IS 'Fecha de vigencia hasta de la matriz';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO.ESTADO IS 'Estado del cuadrante en la matriz de riesgo: ACTIVO, INACTIVO';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO.USUARIO_AUDITORIA IS 'Usuario que modifico el registro por última vez';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO.FECHA_AUDITORIA IS 'Fecha en que se modificó el registro por última vez';


CREATE TABLE PRI_MATRIZ_RIESGO_CUADRANTE
(
  ID_MATRIZ_RIESGO_CUADRANTE  NUMBER(10)        NOT NULL,
  ID_MATRIZ_RIESGO            NUMBER(10)        NOT NULL,
  NUMERO_CUADRANTE            NUMBER(8),
  VALOR_EJE_X_DESDE           NUMBER(20,2),
  VALOR_EJE_X_HASTA           NUMBER(20,2),
  VALOR_EJE_Y_DESDE           NUMBER(20,2),
  VALOR_EJE_Y_HASTA           NUMBER(20,2),
  COLOR                       VARCHAR2(50 BYTE),
  ESTADO                      VARCHAR2(30 CHAR) NOT NULL,
  USUARIO_AUDITORIA           VARCHAR2(50 CHAR) DEFAULT USER NOT NULL,
  FECHA_AUDITORIA             DATE              DEFAULT SYSDATE               NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PRI_MATRIZ_RIESGO_CUADRANTE IS 'Contiene la configuración de los cuadrantes de la matriz de riesgo';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO_CUADRANTE.ID_MATRIZ_RIESGO_CUADRANTE IS 'Identificador único de registro en PRI_MATRIZ_RIESGO_CUADRANTE';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO_CUADRANTE.ID_MATRIZ_RIESGO IS 'Identificador único de registro en PRI_MATRIZ_RIESGO';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO_CUADRANTE.NUMERO_CUADRANTE IS 'Número del cuadrante de la matriz de riesgo de 1 a n';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO_CUADRANTE.VALOR_EJE_X_DESDE IS 'Valor desde del eje x del cuadrante';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO_CUADRANTE.VALOR_EJE_X_HASTA IS 'Valor hasta del eje x del cuadrante';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO_CUADRANTE.VALOR_EJE_Y_DESDE IS 'Valor desde del eje y del cuadrante';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO_CUADRANTE.VALOR_EJE_Y_HASTA IS 'Valor hasta del eje y del cuadrante';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO_CUADRANTE.COLOR IS 'Color que el e corresponde al cuadrante';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO_CUADRANTE.ESTADO IS 'Estado del cuadrante en la matriz de riesgo: ACTIVO, INACTIVO';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO_CUADRANTE.USUARIO_AUDITORIA IS 'Usuario que modifico el registro por última vez';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO_CUADRANTE.FECHA_AUDITORIA IS 'Fecha en que se modificó el registro por última vez';


CREATE TABLE PRI_PERFIL
(
  ID_PERFIL             NUMBER(10)              NOT NULL,
  NIT                   VARCHAR2(20 CHAR),
  PERIODO               NUMBER(10)              NOT NULL,
  ID_MATRIZ_RIESGO      NUMBER(10)              NOT NULL,
  SEGMENTO              VARCHAR2(50 CHAR)       NOT NULL,
  FECHA_DESDE           DATE,
  PESO                  NUMBER(20,4),
  VALOR_PERFIL          NUMBER(20,4),
  VALOR_EJE_X           NUMBER(20,4),
  VALOR_EJE_Y           NUMBER(20,4),
  VALOR_INCUMPLIMIENTO  NUMBER(20,4),
  VALOR_LOG             NUMBER(20,4),
  NUMERO_CUADRANTE      NUMBER(8),
  USUARIO_AUDITORIA     VARCHAR2(50 CHAR)       DEFAULT USER                  NOT NULL,
  FECHA_AUDITORIA       DATE                    DEFAULT SYSDATE               NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PRI_PERFIL IS 'Contiene el valor del perfil de cada contribuyente';

COMMENT ON COLUMN PRI_PERFIL.ID_PERFIL IS 'Identificador único de registro en PRI_PERFIL';

COMMENT ON COLUMN PRI_PERFIL.NIT IS 'Numero de identificación tributario del contribuyente';

COMMENT ON COLUMN PRI_PERFIL.PERIODO IS 'Periodo gravable formato YYYYMM al que corresponde el perfil del contribuyente';

COMMENT ON COLUMN PRI_PERFIL.ID_MATRIZ_RIESGO IS 'Identificador único de registro en PRI_MATRIZ_RIESGO';

COMMENT ON COLUMN PRI_PERFIL.SEGMENTO IS 'Nombre del segmento al cual pertenece el contribuyente: ESPECIAL, ESPECIAL MEDIANO, RESTO, PEQUEÑO';

COMMENT ON COLUMN PRI_PERFIL.FECHA_DESDE IS 'Fecha de vigencia desde el perfil';

COMMENT ON COLUMN PRI_PERFIL.PESO IS 'Valor del peso ponderado del contribuyente dentro de todo el universo de contribuyentes del segmento, todos los pesos deben sumar 1';

COMMENT ON COLUMN PRI_PERFIL.VALOR_PERFIL IS 'Valor del índice de Perfil integral de Cumplimiento';

COMMENT ON COLUMN PRI_PERFIL.VALOR_EJE_X IS 'Valor calculado del eje x de la matriz de riesgo, que corresponde al valor ponderado del valor del incumplimiento';

COMMENT ON COLUMN PRI_PERFIL.VALOR_EJE_Y IS 'Valor calculado del eje y de la matriz de riesgo, que corresponde al valor del perfil de riesgo';

COMMENT ON COLUMN PRI_PERFIL.NUMERO_CUADRANTE IS 'Numero del cuadrante de la matriz de riesgo de 1 a 20 que corresponde a la ubicación del contribuyente en la matriz de riesgo';

COMMENT ON COLUMN PRI_PERFIL.USUARIO_AUDITORIA IS 'Usuario que modifico el registro por última vez';

COMMENT ON COLUMN PRI_PERFIL.FECHA_AUDITORIA IS 'Fecha en que se modificó el registro por última vez';


CREATE TABLE PRI_SEGMENTO
(
  ID_SEGMENTO        NUMBER(10)                 NOT NULL,
  NOMBRE             VARCHAR2(200 CHAR),
  ESTADO             VARCHAR2(30 CHAR)          NOT NULL,
  USUARIO_AUDITORIA  VARCHAR2(50 CHAR)          DEFAULT USER                  NOT NULL,
  FECHA_AUDITORIA    DATE                       DEFAULT SYSDATE               NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PRI_SEGMENTO IS 'Contiene la definición de los segementos de clasificacion de contribuyentes, como su tamaño, Regimen y Region';

COMMENT ON COLUMN PRI_SEGMENTO.ID_SEGMENTO IS 'Identificador único de registro en PRI_SEGMENTO';

COMMENT ON COLUMN PRI_SEGMENTO.NOMBRE IS 'Nombre del segmento';

COMMENT ON COLUMN PRI_SEGMENTO.ESTADO IS 'Estado del segmento: ACTIVO, INACTIVO';

COMMENT ON COLUMN PRI_SEGMENTO.USUARIO_AUDITORIA IS 'Usuario que modifico el registro por última vez';

COMMENT ON COLUMN PRI_SEGMENTO.FECHA_AUDITORIA IS 'Fecha en que se modificó el registro por última vez';


CREATE TABLE PRI_VARIABLE
(
  ID_VARIABLE               NUMBER(10)          NOT NULL,
  NOMBRE                    VARCHAR2(200 CHAR),
  FUENTE_SISTEMA            VARCHAR2(100 CHAR),
  FUENTE_INFORMACION        VARCHAR2(1000 CHAR),
  FORMULA                   VARCHAR2(1000 CHAR),
  PERIODICIDAD              VARCHAR2(50 CHAR),
  PROCEDIMIENTO_BASE_DATOS  VARCHAR2(100 CHAR),
  ESTADO                    VARCHAR2(30 CHAR)   NOT NULL,
  USUARIO_AUDITORIA         VARCHAR2(50 CHAR)   DEFAULT USER                  NOT NULL,
  FECHA_AUDITORIA           DATE                DEFAULT SYSDATE               NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PRI_VARIABLE IS 'Contiene la definición de la lista de variables para el cálculo del perfil de riesgo';

COMMENT ON COLUMN PRI_VARIABLE.ID_VARIABLE IS 'Identificador único de registro en PRI_VARIABLE';

COMMENT ON COLUMN PRI_VARIABLE.NOMBRE IS 'Nombre de la variable';

COMMENT ON COLUMN PRI_VARIABLE.FUENTE_SISTEMA IS 'Nombre del sistema o modulo que almacena el valor de la variable';

COMMENT ON COLUMN PRI_VARIABLE.FUENTE_INFORMACION IS 'Descripción de la fuente de información, tabla, columna donde se almacena el valor de la variable o SQL para generar o consultar el valor';

COMMENT ON COLUMN PRI_VARIABLE.FORMULA IS 'Descripción de la fórmula utilizada para generar o calcular el valor de la variable';

COMMENT ON COLUMN PRI_VARIABLE.PERIODICIDAD IS 'Frecuencia de cálculo de la variable: ANUAL, MENSUAL, DIARIO';

COMMENT ON COLUMN PRI_VARIABLE.PROCEDIMIENTO_BASE_DATOS IS 'Nombre del procedimiento almacenado Oracle que extrae el valor de la variable';

COMMENT ON COLUMN PRI_VARIABLE.ESTADO IS 'Estado de la variable: ACTIVO, INACTIVO';

COMMENT ON COLUMN PRI_VARIABLE.USUARIO_AUDITORIA IS 'Usuario que modifico el registro por última vez';

COMMENT ON COLUMN PRI_VARIABLE.FECHA_AUDITORIA IS 'Fecha en que se modificó el registro por última vez';


CREATE UNIQUE INDEX PRI_MATRIZ_RIESGO_CUAD_PK ON PRI_MATRIZ_RIESGO_CUADRANTE
(ID_MATRIZ_RIESGO_CUADRANTE)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PRI_MATRIZ_RIESGO_PK ON PRI_MATRIZ_RIESGO
(ID_MATRIZ_RIESGO)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PRI_PERFIL_PK ON PRI_PERFIL
(ID_PERFIL)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PRI_SEGMENTO_PK ON PRI_SEGMENTO
(ID_SEGMENTO)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PRI_VARIABLE_PK ON PRI_VARIABLE
(ID_VARIABLE)
LOGGING
NOPARALLEL;


CREATE TABLE PRI_FUENTES_INFORMACION
(
  ID_FUENTE_INFORMACION  NUMBER(10)             NOT NULL,
  NIT                    VARCHAR2(20 CHAR),
  PERIODO                NUMBER(10)             NOT NULL,
  ID_VARIABLE            NUMBER(10)             NOT NULL,
  ID_SEGMENTO            NUMBER(10)             NOT NULL,
  VALOR_VARIABLE         NUMBER(20,2),
  USUARIO_AUDITORIA      VARCHAR2(50 CHAR)      DEFAULT USER                  NOT NULL,
  FECHA_AUDITORIA        DATE                   DEFAULT SYSDATE               NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PRI_FUENTES_INFORMACION IS 'Contiene los valores de las variables para todos los contribuyentes para un periodo determinado';

COMMENT ON COLUMN PRI_FUENTES_INFORMACION.ID_FUENTE_INFORMACION IS 'Identificador único de registro en PRI_FUENTES_INFORMACION';

COMMENT ON COLUMN PRI_FUENTES_INFORMACION.NIT IS 'Numero de identificación tributario del contribuyente';

COMMENT ON COLUMN PRI_FUENTES_INFORMACION.PERIODO IS 'Periodo gravable formato YYYYMM al que corresponde la fuente de información';

COMMENT ON COLUMN PRI_FUENTES_INFORMACION.ID_VARIABLE IS 'Identificador único de registro en PRI_VARIABLE';

COMMENT ON COLUMN PRI_FUENTES_INFORMACION.VALOR_VARIABLE IS 'Valor de la variable';

COMMENT ON COLUMN PRI_FUENTES_INFORMACION.USUARIO_AUDITORIA IS 'Usuario que modifico el registro por última vez';

COMMENT ON COLUMN PRI_FUENTES_INFORMACION.FECHA_AUDITORIA IS 'Fecha en que se modificó el registro por última vez';


CREATE TABLE PRI_MATRIZ_RIESGO_VARIABLE
(
  ID_MATRIZ_RIESGO_VARIABLE  NUMBER(10)         NOT NULL,
  ID_MATRIZ_RIESGO           NUMBER(10)         NOT NULL,
  ID_VARIABLE                NUMBER(10)         NOT NULL,
  ID_SEGMENTO                VARCHAR2(50 CHAR)  NOT NULL,
  FUENTE_PESO_Y              NUMBER(20,2),
  FUENTE_EJE_X               VARCHAR2(2 BYTE),
  FUENTE_EJE_Y               VARCHAR2(2 BYTE),
  FUENTE_PESO_CONTRIBUYENTE  VARCHAR2(2 BYTE),
  ESTADO                     VARCHAR2(30 CHAR)  NOT NULL,
  USUARIO_AUDITORIA          VARCHAR2(50 CHAR)  DEFAULT USER                  NOT NULL,
  FECHA_AUDITORIA            DATE               DEFAULT SYSDATE               NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PRI_MATRIZ_RIESGO_VARIABLE IS 'Contiene la definición de la lista de variables para el cálculo del perfil de riesgo para un segmento (especial grande, especial mediano, resto, pequeño) determinado';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO_VARIABLE.ID_MATRIZ_RIESGO_VARIABLE IS 'Identificador único de registro en PRI_MATRIZ_RIESGO_VARIABLE';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO_VARIABLE.ID_MATRIZ_RIESGO IS 'Identificador único de registro en PRI_MATRIZ_RIESGO';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO_VARIABLE.ID_VARIABLE IS 'Identificador único de registro en PRI_VARIABLE';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO_VARIABLE.ID_SEGMENTO IS 'Nombre del segmento (ESPECIAL, MEDIANO, RESTO, PEQUENIO)';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO_VARIABLE.FUENTE_PESO_Y IS 'Valor del peso ponderado de la variable dentro del grupo de variables del segmento';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO_VARIABLE.FUENTE_EJE_X IS 'Indicativo SI/NO que dice si la variable hace parte del cálculo del peso ponderado del incumplimiento que corresponde al eje X de la matriz';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO_VARIABLE.FUENTE_EJE_Y IS 'Indicativo SI/NO que dice si la variable hace parte del cálculo del perfil de riesgo que corresponde al eje X de la matriz';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO_VARIABLE.FUENTE_PESO_CONTRIBUYENTE IS 'Indicativo SI/NO que dice si la variable participa en el cálculo del peso del contribuyente dentro del grupo de contribuyentes del segmento';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO_VARIABLE.ESTADO IS 'Estado de la variable: ACTIVO, INACTIVO';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO_VARIABLE.USUARIO_AUDITORIA IS 'Usuario que modifico el registro por última vez';

COMMENT ON COLUMN PRI_MATRIZ_RIESGO_VARIABLE.FECHA_AUDITORIA IS 'Fecha en que se modificó el registro por última vez';


CREATE TABLE PRI_PERFIL_VARIABLE
(
  ID_PERFIL_VARIABLE         NUMBER(10)         NOT NULL,
  ID_PERFIL                  NUMBER(10)         NOT NULL,
  ID_MATRIZ_RIESGO_VARIABLE  NUMBER(10)         NOT NULL,
  VALOR_VARIABLE             NUMBER(20,4)       NOT NULL,
  VALOR_NORMALIZADO          NUMBER(20,4)       NOT NULL,
  VALOR_RIESGO               NUMBER(20,4)       NOT NULL,
  USUARIO_AUDITORIA          VARCHAR2(50 CHAR)  DEFAULT USER                  NOT NULL,
  FECHA_AUDITORIA            DATE               DEFAULT SYSDATE               NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE PRI_PERFIL_VARIABLE IS 'Contiene los valores de las variables de un contribuyente para un periodo y que son la fuente para el cálculo del perfil';

COMMENT ON COLUMN PRI_PERFIL_VARIABLE.ID_PERFIL_VARIABLE IS 'Identificador único de registro en PRI_PERFIL_VARIABLE';

COMMENT ON COLUMN PRI_PERFIL_VARIABLE.ID_PERFIL IS 'Identificador único de registro en PRI_PERFIL';

COMMENT ON COLUMN PRI_PERFIL_VARIABLE.ID_MATRIZ_RIESGO_VARIABLE IS 'Identificador único de registro en PRI_MATRIZ_RIESGO_VARIABLE';

COMMENT ON COLUMN PRI_PERFIL_VARIABLE.VALOR_VARIABLE IS 'Valor de la variable';

COMMENT ON COLUMN PRI_PERFIL_VARIABLE.VALOR_NORMALIZADO IS 'Valor normalizado del indicador generado a partir del valor de la variable';

COMMENT ON COLUMN PRI_PERFIL_VARIABLE.VALOR_RIESGO IS 'Valor de riesgo que esta entre 0 y 1 que se genera a partir del valor normalizado del indicador';

COMMENT ON COLUMN PRI_PERFIL_VARIABLE.USUARIO_AUDITORIA IS 'Usuario que modifico el registro por última vez';

COMMENT ON COLUMN PRI_PERFIL_VARIABLE.FECHA_AUDITORIA IS 'Fecha en que se modificó el registro por última vez';


CREATE UNIQUE INDEX PRI_FUENTES_INFORMACION_PK ON PRI_FUENTES_INFORMACION
(ID_FUENTE_INFORMACION)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PRI_MATRIZ_RIESGO_VARI_PK ON PRI_MATRIZ_RIESGO_VARIABLE
(ID_MATRIZ_RIESGO_VARIABLE)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PRI_PERFIL_VARIABLE_PK ON PRI_PERFIL_VARIABLE
(ID_PERFIL_VARIABLE)
LOGGING
NOPARALLEL;


ALTER TABLE PRI_MATRIZ_RIESGO ADD (
  CONSTRAINT PRI_MATRIZ_RIESGO_PK
  PRIMARY KEY
  (ID_MATRIZ_RIESGO)
  USING INDEX PRI_MATRIZ_RIESGO_PK);

ALTER TABLE PRI_MATRIZ_RIESGO_CUADRANTE ADD (
  CONSTRAINT PRI_MATRIZ_RIESGO_CUAD_PK
  PRIMARY KEY
  (ID_MATRIZ_RIESGO_CUADRANTE)
  USING INDEX PRI_MATRIZ_RIESGO_CUAD_PK);

ALTER TABLE PRI_PERFIL ADD (
  CONSTRAINT PRI_PERFIL_PK
  PRIMARY KEY
  (ID_PERFIL)
  USING INDEX PRI_PERFIL_PK);

ALTER TABLE PRI_SEGMENTO ADD (
  CONSTRAINT PRI_SEGMENTO_PK
  PRIMARY KEY
  (ID_SEGMENTO)
  USING INDEX PRI_SEGMENTO_PK);

ALTER TABLE PRI_VARIABLE ADD (
  CONSTRAINT PRI_VARIABLE_PK
  PRIMARY KEY
  (ID_VARIABLE)
  USING INDEX PRI_VARIABLE_PK);

ALTER TABLE PRI_FUENTES_INFORMACION ADD (
  CONSTRAINT PRI_FUENTES_INFORMACION_PK
  PRIMARY KEY
  (ID_FUENTE_INFORMACION)
  USING INDEX PRI_FUENTES_INFORMACION_PK);

ALTER TABLE PRI_MATRIZ_RIESGO_VARIABLE ADD (
  CONSTRAINT PRI_MATRIZ_RIESGO_VARI_PK
  PRIMARY KEY
  (ID_MATRIZ_RIESGO_VARIABLE)
  USING INDEX PRI_MATRIZ_RIESGO_VARI_PK);

ALTER TABLE PRI_PERFIL_VARIABLE ADD (
  CONSTRAINT PRI_PERFIL_VARIABLE_PK
  PRIMARY KEY
  (ID_PERFIL_VARIABLE)
  USING INDEX PRI_PERFIL_VARIABLE_PK);

ALTER TABLE PRI_MATRIZ_RIESGO_CUADRANTE ADD (
  CONSTRAINT FK_MATRIZ_RIESGO_CUAD_1 
  FOREIGN KEY (ID_MATRIZ_RIESGO) 
  REFERENCES PRI_MATRIZ_RIESGO (ID_MATRIZ_RIESGO));

ALTER TABLE PRI_PERFIL ADD (
  CONSTRAINT FK_PRI_PERFIL_1 
  FOREIGN KEY (ID_MATRIZ_RIESGO) 
  REFERENCES PRI_MATRIZ_RIESGO (ID_MATRIZ_RIESGO));

ALTER TABLE PRI_FUENTES_INFORMACION ADD (
  CONSTRAINT FK_PRI_FUENTES_INFORMACION_1 
  FOREIGN KEY (ID_VARIABLE) 
  REFERENCES PRI_VARIABLE (ID_VARIABLE),
  CONSTRAINT FK_PRI_FUENTES_INFORMACION_2 
  FOREIGN KEY (ID_SEGMENTO) 
  REFERENCES PRI_SEGMENTO (ID_SEGMENTO));

ALTER TABLE PRI_MATRIZ_RIESGO_VARIABLE ADD (
  CONSTRAINT FK_PRI_MATRIZ_RIESGO_VARI_1 
  FOREIGN KEY (ID_VARIABLE) 
  REFERENCES PRI_VARIABLE (ID_VARIABLE),
  CONSTRAINT FK_PRI_MATRIZ_RIESGO_VARI_2 
  FOREIGN KEY (ID_MATRIZ_RIESGO) 
  REFERENCES PRI_MATRIZ_RIESGO (ID_MATRIZ_RIESGO));

ALTER TABLE PRI_PERFIL_VARIABLE ADD (
  CONSTRAINT FK_PRI_PERFIL_VARIABLE_1 
  FOREIGN KEY (ID_PERFIL) 
  REFERENCES PRI_PERFIL (ID_PERFIL),
  CONSTRAINT FK_PRI_PERFIL_VARIABLE_2 
  FOREIGN KEY (ID_MATRIZ_RIESGO_VARIABLE) 
  REFERENCES PRI_MATRIZ_RIESGO_VARIABLE (ID_MATRIZ_RIESGO_VARIABLE));
